# Cargo configuration for the rust-watcher project
[build]
# Use moderate parallelism for good build performance
jobs = 4
rustc-wrapper = "./sccache.exe"  # Uncomment if you have sccache.exe in the project root

[env]
# Standard test configuration
RUST_BACKTRACE = "1" # Enable backtraces for debugging

[target.x86_64-pc-windows-msvc]
# Windows-specific optimizations
rustflags = ["-C", "target-cpu=native"]
